### PR TITLE
feat: add overwrite functionality for invalid Pattern

### PR DESCRIPTION
**Pull request by eminaktas**
#710

### CODE REVIEW

**Comment by alombarte** [comment]
Hi @eminaktas ,

I feel like removing the error management during the validation will bring unintended consequences.

**Comment by eminaktas** [comment]
> Hi @eminaktas ,
> 
> I feel like removing the error management during the validation will bring unintended consequences.

Do you want to me keep the functioning as it was or just not remove `EndpointMatchError`?

**Comment by eminaktas** [comment]
@alombarte just added back `EndpointMatchError` method.

**Comment by eminaktas** [comment]
@kpacha updated as you mentioned. Thanks for the review.

**Review by kpacha — APPROVED** [review]

**Comment by kpacha** [comment]
Thanks for the contribution!

**Pull request merged**
