### PR TITLE
add DisableStrictREST to parseableServiceConfig

### PR DESCRIPTION
**Pull request by nodar963**
Signed-off-by: Nodar Jarrar [nodar963@gmail.com](mailto:nodar963@gmail.com)

### CODE REVIEW

**Comment by nodar963** [comment]
#600

**Comment by nodar963** [comment]
#600 
#599

**Comment by nodar963** [comment]
CI failed because "io/ioutil" is now deprecated, how should we proceed?

**Review by kpacha — APPROVED** [review]

**Comment by kpacha** [comment]
thanks for the contribution!

**Pull request merged**
