### PR TITLE
Include all successful http status code in default http hnadler

### PR DESCRIPTION
**Pull request by abdulrahmank**
PR for issue: https://github.com/devopsfaith/krakend/issues/283

### CODE REVIEW

**Comment by kpacha** [comment]
can you add some integration tests? (https://github.com/devopsfaith/krakend/tree/master/test)

**Comment by kpacha** [comment]
@abdulrahmank did you see my last comment?

I think changes as important as this one should be covered also at the integration tests

**Comment by abdulrahmank** [comment]
Hi @kpacha   Sorry, got held up. Will add the integration tests. and update. Thank you

**Comment by alombarte** [comment]
Hi @abdulrahmank , shall we keep this PR open? Or do you think that it can be finished and merged?

**Comment by alombarte** [comment]
Closing for inactivity

**Pull request closed without merging**
